### ISSUE TITLE
NameError: name 'ChromeDriverManagerException' is not defined

### ISSUE THREAD

**Issue by ishandutta2007** [iamseyedalipro/ChatGPTAutomation#1]
I am trying to do as specified in docs.
This is the only code I have

First did this:

```
pip install ChatGPTAutomation
```
then in python:

```
from chatgpt_automation.chatgpt_automation import ChatGPTAutomation
chat_bot = ChatGPTAutomation()
chat_bot.send_prompt_to_chatgpt("Hello, ChatGPT!")
```
My python version is 3.8.0

**Comment by iamseyedalipro** [comment]
Sorry for the long delay in replying, it seems like there was a problem with libary and I didn't know it was fixed.
