### ISSUE TITLE
Problem with chat_bot.return_last_response()

### ISSUE THREAD

**Issue by alisaandutova** [iamseyedalipro/ChatGPTAutomation#2]
The problem is getting the "response" result.
 response = self.driver.find_elements(*ChatGPTLocators.CHAT_GPT_CONVERSION)[-1]
 Before the update on April 29, everything worked. After updating, the result is empty. Reports that there is no "text" element in the "response" variable. There may be a problem with the update or “chat.openai.com” has changed the paths. Perhaps "CHAT_GPT_CONVERSION" is deprecated. Please help me solve the problem. Thanks in advance.

**Comment by iamseyedalipro** [comment]
Thank you for informing me, the problem has been solved, please update your lib and use it
have a fun day :)

**Comment by alisaandutova** [comment]
> Спасибо, что сообщили мне, проблема решена, пожалуйста, обновите свою библиотеку и используйте ее, приятного дня :)

Thank you for your prompt assistance. The project is very cool, good luck in your new achievements.

**Comment by iamseyedalipro** [comment]
you're welcome
Please notify me of any problems with the project
thank you
